name: Master

on:
  push:
    branches:
      - master

jobs:
  linters:
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install poetry tox

      - name: Run flake8 for ${{ matrix.python-version }}
        env:
          TOXENV: flake8
        run: tox

      - name: Run mypy for ${{ matrix.python-version }}
        env:
          TOXENV: mypy
        run: tox

      # - name: Send notification to Telegram
      #   if: always()
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHAT }}
      #     token: ${{ secrets.TELEGRAM_SECRET }}
      #     args: ${{ github.repository }} linters for `master` - ${{ job.status }}

  tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install poetry tox

      # - name: Run unit tests for ${{ matrix.python-version }}
      #   env:
      #     TOXENV: unit
      #   run: tox

      - name: Run integration tests for ${{ matrix.python-version }}
        env:
          TOXENV: integration
        run: tox

      - name: Get coverage report
        env:
          TOXENV: report
        run: tox

      # - name: Send notification to Telegram
      #   if: always()
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_CHAT }}
      #     token: ${{ secrets.TELEGRAM_SECRET }}
      #     args: ${{ github.repository }} tests for `master` - ${{ job.status }}

