name: Pull requests

on:
  pull_request:


jobs:
  linters:
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install poetry tox

      - name: Run flake8 for ${{ matrix.python-version }}
        env:
          TOXENV: flake8
        run: tox

      - name: Run mypy for ${{ matrix.python-version }}
        env:
          TOXENV: mypy
        run: tox

  tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install poetry tox

      - name: Run tests for ${{ matrix.python-version }}
        env:
          TOXENV: tests
        run: tox

      - name: Get coverage report
        env:
          TOXENV: report
        run: tox
